version: "3"
services:
  # Nginx ################################################
  nginx:
    build: ./nginx
    environment:
      TZ: Asia/Tokyo
    expose:
      - "80"
    depends_on:
      - php-fpm
    volumes:
      - "./web:/var/www/web:cached"
      - "./log/nginx:/var/log/nginx"
    ports:
      - "80:80"
  # php-fpm ################################################
  php-fpm:
    build: ./php-fpm
    expose:
      - "9000"
    depends_on:
      - postgres
    volumes:
      - "./web:/var/www/web:cached"
  # MySQL ################################################
  # mysql:
  #   build: ./mysql
  #   environment:
  #     MYSQL_DATABASE: db
  #     MYSQL_ROOT_PASSWORD: root
  #     TZ: Asia/Tokyo
  #   expose:
  #     - "3306"
  #   volumes:
  #     - "./.data/mysql:/var/lib/mysql"
  #     - "./log/mysql:/var/log/mysql"
  #   ports:
  #     - "3306:3306"
  # PostgreSQL ################################################
  postgres:
    build: ./postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - "./.data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"